local f = io.open('GENERAL.lua', "rb")
local content = f:read("*all")
f:close()
os.execute('killall -9 GENERAL.sh')
os.execute('killall -9 tg')
os.execute('rm -rf GENERAL.lua')
os.execute('git reset --hard origin/master')
os.execute('git pull')
local fi = io.open('GENERAL.lua', "w+")
fi:write(tostring(content))
fi:close()
os.execute('chmod 777 tg && chmod 777 GENERAL.sh')
os.execute('screen ./GENERAL.sh')
